import React, { useEffect, useMemo, useState } from 'react';
import { FileSpreadsheet, FileText, Search, ShieldCheck } from 'lucide-react';
import { exportReport, getReportData } from '@/api/portalClient';
import { EmptyHint, PageHeader, PrimaryButton, SecondaryButton } from '@/components/payroll/PageElements';

const Card = ({ children, className = '' }) => <section className={`rounded-xl border border-border bg-card p-5 ${className}`}>{children}</section>;
const inputClass = 'h-10 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';

export default function AuditLogs() {
  const [filters, setFilters] = useState({ search: '', month: '', year: '' });
  const [data, setData] = useState({ rows: [] });
  const [error, setError] = useState('');
  const [busy, setBusy] = useState('');
  const load = async (next = filters) => { setBusy('load'); try { setData(await getReportData('audit_trail', next)); setError(''); } catch (err) { setError(err.message); } finally { setBusy(''); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const actions = useMemo(() => [...new Set((data.rows || []).map((item) => item.action))].sort(), [data.rows]);
  const [action, setAction] = useState('');
  const visible = action ? data.rows.filter((item) => item.action === action) : data.rows;
  const download = async (format) => { setBusy(format); try { saveBlob(await exportReport('audit_trail', format, filters)); } catch (err) { setError(err.message); } finally { setBusy(''); } };
  return <div className="space-y-6"><PageHeader title="Audit Logs" description="Immutable operational evidence showing who changed what, when, and from which IP address." actions={<><SecondaryButton disabled={Boolean(busy)} onClick={() => download('pdf')}><FileText className="h-4 w-4" /> Export PDF</SecondaryButton><PrimaryButton disabled={Boolean(busy)} onClick={() => download('xlsx')}><FileSpreadsheet className="h-4 w-4" /> Export Excel</PrimaryButton></>} />
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}
    <Card><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr,180px,140px,220px,auto]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input className={`${inputClass} w-full pl-9`} value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search user, action, staff or values" /></label><input className={`${inputClass} w-full`} type="month" value={filters.month} onChange={(event) => setFilters({ ...filters, month: event.target.value })} /><input className={`${inputClass} w-full`} type="number" placeholder="Year" value={filters.year} onChange={(event) => setFilters({ ...filters, year: event.target.value })} /><select className={`${inputClass} w-full`} value={action} onChange={(event) => setAction(event.target.value)}><option value="">All actions</option>{actions.map((item) => <option key={item}>{item}</option>)}</select><PrimaryButton disabled={busy === 'load'} onClick={() => load()}><Search className="h-4 w-4" /> Filter</PrimaryButton></div></Card>
    <Card><div className="grid gap-3 md:hidden">{visible.map((event) => <article key={event.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{event.actorName}</p><p className="text-xs text-muted-foreground">{event.dateTime}</p></div><span className="rounded-md bg-muted px-2 py-1 text-[10px] font-bold">{event.action?.replaceAll('_', ' ')}</span></div><p className="mt-3 break-words text-sm">{event.target}</p>{(event.oldValue || event.newValue) && <div className="mt-3 grid gap-2 rounded-lg bg-muted/40 p-3 text-xs"><p><b>Before:</b> {display(event.oldValue)}</p><p><b>After:</b> {display(event.newValue)}</p></div>}<p className="mt-3 font-mono text-[11px] text-muted-foreground">IP {event.ipAddress}</p></article>)}{!visible.length && <EmptyHint>No audit activity matched the selected filters.</EmptyHint>}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="border-b border-border text-xs uppercase text-muted-foreground"><tr><th className="pb-3">Date and time</th><th className="pb-3">User</th><th className="pb-3">Action</th><th className="pb-3">Old value</th><th className="pb-3">New value</th><th className="pb-3">Record / details</th><th className="pb-3">IP address</th></tr></thead><tbody>{visible.map((event) => <tr key={event.id} className="border-b border-border/60 align-top last:border-0"><td className="whitespace-nowrap py-3">{event.dateTime}</td><td><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><ShieldCheck className="h-4 w-4" /></span><span className="font-semibold">{event.actorName}</span></div></td><td><span className="rounded-md bg-muted px-2 py-1 text-xs font-bold">{event.action?.replaceAll('_', ' ')}</span></td><td className="max-w-xs break-words text-xs">{display(event.oldValue)}</td><td className="max-w-xs break-words text-xs">{display(event.newValue)}</td><td className="max-w-sm break-words text-xs text-muted-foreground">{event.target}</td><td className="font-mono text-xs">{event.ipAddress}</td></tr>)}</tbody></table>{!visible.length && <EmptyHint>No audit activity matched the selected filters.</EmptyHint>}</div></Card>
  </div>;
}

function display(value) { if (value === null || value === undefined || value === '') return '—'; return typeof value === 'object' ? JSON.stringify(value) : String(value); }
function saveBlob({ blob, filename }) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
