import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Columns3, Eye, FileSpreadsheet, FileText, Filter, Search, ShieldCheck } from 'lucide-react';
import { exportReport, getReportData } from '@/api/portalClient';
import { EmptyHint, PageHeader, PrimaryButton, SecondaryButton } from '@/components/payroll/PageElements';
import { toast } from '@/components/ui/use-toast';
import ResponsiveSheet from '@/components/ui/responsive-sheet';

const inputClass = 'h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';
const defaultFilters = { search: '', action: '', dateFrom: '', dateTo: '' };
const defaultColumns = ['dateTime', 'actorName', 'action', 'target', 'ipAddress'];
const Card = ({ children, className = '' }) => <section className={`rounded-xl border border-border bg-card p-4 sm:p-5 ${className}`}>{children}</section>;

export default function AuditLogs() {
  const [filters, setFilters] = useState(defaultFilters);
  const [data, setData] = useState({ columns: [], rows: [], pagination: {} });
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [visibleColumns, setVisibleColumns] = useState(defaultColumns);
  const [selected, setSelected] = useState(null);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const [filterName, setFilterName] = useState('');
  const [savedFilters, setSavedFilters] = useState([]);
  const [filtersOpen, setFiltersOpen] = useState(false);
  useEffect(() => { window.localStorage.removeItem('bcb_audit_saved_filters'); }, []);

  const load = async (next = filters, nextPage = page, nextSize = pageSize) => { setBusy('load'); try { setData(await getReportData('audit_trail', { ...next, page: nextPage, pageSize: nextSize })); setError(''); } catch (err) { setError(err.message); } finally { setBusy(''); } };
  useEffect(() => { load(defaultFilters, 1, pageSize); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo(() => data.columns.filter((column) => visibleColumns.includes(column.key)), [data.columns, visibleColumns]);
  const actions = useMemo(() => [...new Set([filters.action, ...data.rows.map((row) => row.action)].filter(Boolean))].sort(), [data.rows, filters.action]);
  const apply = (next = filters) => { setPage(1); load(next, 1, pageSize); };
  const shortcut = (key) => { const range = dateRange(key); const next = { ...filters, ...range }; setFilters(next); apply(next); };
  const saveFilter = () => { const name = filterName.trim(); if (!name) return; const next = [...savedFilters.filter((item) => item.name !== name), { name, filters }]; setSavedFilters(next); setFilterName(''); toast.success('The audit filter is available only for this page visit.', { title: 'Temporary filter saved' }); };
  const applySavedFilter = (index) => { const item = savedFilters[index]; if (!item) return; const next = { ...defaultFilters, ...item.filters }; setFilters(next); apply(next); };
  const download = async (format) => { setBusy(format); try { saveBlob(await exportReport('audit_trail', format, filters)); toast.success('Every matching audit event was included in the export.', { title: 'Audit export ready' }); } catch (err) { setError(err.message); } finally { setBusy(''); } };

  return <div className="space-y-6">
    <PageHeader title="Audit Logs" description="Review immutable evidence of who changed what, when, and from which IP address." />
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}
    <Card>
      <button type="button" onClick={() => setFiltersOpen((current) => !current)} className="mb-3 flex min-h-11 w-full items-center justify-between rounded-lg border border-border px-3 text-sm font-semibold md:hidden" aria-expanded={filtersOpen}><span className="flex items-center gap-2"><Filter className="h-4 w-4 text-primary" /> Audit filters</span><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] text-primary">{Object.values(filters).filter(Boolean).length} active</span></button>
      <div className={`${filtersOpen ? 'block' : 'hidden'} md:block`}>
      <div className="mb-4 flex flex-wrap items-center gap-2"><CalendarDays className="h-4 w-4 text-primary" />{[['today','Today'],['7days','Last 7 days'],['month','This month'],['year','This year'],['all','All time']].map(([key,label]) => <button key={key} onClick={() => shortcut(key)} className="rounded-full border border-border px-3 py-1.5 text-xs font-semibold hover:border-primary hover:text-primary">{label}</button>)}</div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr,220px,170px,170px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input aria-label="Search audit logs" className={`${inputClass} pl-9`} value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search users, actions, records or values" /></label><select aria-label="Filter audit logs by action" className={inputClass} value={filters.action} onChange={(event) => setFilters({ ...filters, action: event.target.value })}><option value="">All actions</option>{actions.map((item) => <option key={item} value={item}>{cleanAction(item)}</option>)}</select><input className={inputClass} type="date" aria-label="From date" value={filters.dateFrom} onChange={(event) => setFilters({ ...filters, dateFrom: event.target.value })} /><input className={inputClass} type="date" aria-label="To date" value={filters.dateTo} onChange={(event) => setFilters({ ...filters, dateTo: event.target.value })} /></div>
      <div className="mt-4 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-1 flex-wrap gap-2"><input aria-label="Saved audit filter name" className={`${inputClass} max-w-52`} value={filterName} onChange={(event) => setFilterName(event.target.value)} placeholder="Name this filter" /><SecondaryButton onClick={saveFilter} disabled={!filterName.trim()}>Save filter</SecondaryButton><select aria-label="Apply a saved audit filter" className={`${inputClass} max-w-56`} defaultValue="" onChange={(event) => { if (event.target.value) applySavedFilter(Number(event.target.value)); event.target.value = ''; }}><option value="">Saved filters</option>{savedFilters.map((item,index) => <option key={item.name} value={index}>{item.name}</option>)}</select></div><div className="grid grid-cols-2 gap-2 sm:flex"><SecondaryButton onClick={() => { setFilters(defaultFilters); apply(defaultFilters); }}>Clear</SecondaryButton><PrimaryButton disabled={busy === 'load'} onClick={() => { apply(); setFiltersOpen(false); }}><Search className="h-4 w-4" /> Apply filters</PrimaryButton></div></div>
      </div>
    </Card>

    <Card className="border-primary/20 bg-primary/[.025]"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-heading text-lg font-bold">Exported audit report</p><p className="text-sm text-muted-foreground">The screen shows {data.rows.length} events on page {page}; exports contain all {data.pagination?.total ?? data.rows.length} matching events.</p></div><div className="flex flex-col gap-2 sm:flex-row"><SecondaryButton disabled={Boolean(busy)} onClick={() => download('pdf')}><FileText className="h-4 w-4" /> Export all to PDF</SecondaryButton><PrimaryButton disabled={Boolean(busy)} onClick={() => download('xlsx')}><FileSpreadsheet className="h-4 w-4" /> Export all to Excel</PrimaryButton></div></div></Card>

    <Card>
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading text-xl font-bold">On-screen audit events</h2><p className="text-sm text-muted-foreground">Open a record to inspect complete before-and-after values vertically.</p></div><ColumnPicker columns={data.columns} visible={visibleColumns} toggle={(key) => setVisibleColumns((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])} /></div>
      <div className="grid gap-3 md:hidden">{data.rows.map((event) => <article key={event.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{event.actorName}</p><p className="text-xs text-muted-foreground">{event.dateTime}</p></div><span className="rounded-md bg-muted px-2 py-1 text-[10px] font-bold">{cleanAction(event.action)}</span></div><p className="mt-3 break-words text-sm">{event.target || 'System activity'}</p><SecondaryButton className="mt-4 w-full" onClick={() => setSelected(event)}><Eye className="h-4 w-4" /> View evidence</SecondaryButton></article>)}</div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border bg-muted/30 text-xs uppercase text-muted-foreground"><tr>{columns.map((column) => <th key={column.key} className="whitespace-nowrap px-3 py-3">{column.label}</th>)}<th className="px-3 py-3">Details</th></tr></thead><tbody>{data.rows.map((event) => <tr key={event.id} className="border-b border-border/60 align-top last:border-0">{columns.map((column) => <td key={column.key} className="max-w-sm break-words px-3 py-3">{column.key === 'actorName' ? <span className="inline-flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-primary" />{display(event[column.key])}</span> : column.key === 'action' ? <span className="rounded-md bg-muted px-2 py-1 text-xs font-bold">{cleanAction(event.action)}</span> : display(event[column.key])}</td>)}<td className="px-3 py-2"><button onClick={() => setSelected(event)} className="rounded-lg p-2 text-primary hover:bg-primary/10" title="View full event"><Eye className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>
      {!data.rows.length && busy !== 'load' && <EmptyHint>No audit activity matched the selected filters.</EmptyHint>}
      <div className="mt-5 flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between"><select aria-label="Rows per audit page" className={`${inputClass} w-36`} value={pageSize} onChange={(event) => { const size = Number(event.target.value); setPageSize(size); setPage(1); load(filters,1,size); }}><option value="10">10 per page</option><option value="25">25 per page</option><option value="50">50 per page</option><option value="100">100 per page</option></select><div className="flex items-center justify-between gap-3"><SecondaryButton disabled={page <= 1 || Boolean(busy)} onClick={() => { const next = page - 1; setPage(next); load(filters,next,pageSize); }}><ChevronLeft className="h-4 w-4" /> Previous</SecondaryButton><span className="text-sm text-muted-foreground">Page {page} of {data.pagination?.pages || 1}</span><SecondaryButton disabled={page >= (data.pagination?.pages || 1) || Boolean(busy)} onClick={() => { const next = page + 1; setPage(next); load(filters,next,pageSize); }}>Next <ChevronRight className="h-4 w-4" /></SecondaryButton></div></div>
    </Card>
    <AuditDrawer event={selected} columns={data.columns} onClose={() => setSelected(null)} />
  </div>;
}

function ColumnPicker({ columns, visible, toggle }) { return <details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold"><Columns3 className="h-4 w-4" /> Columns ({visible.length}/{columns.length})</summary><div className="absolute right-0 z-20 mt-2 w-64 rounded-xl border border-border bg-card p-3 shadow-xl">{columns.map((column) => <label key={column.key} className="flex cursor-pointer gap-2 rounded-lg px-2 py-2 text-sm hover:bg-muted"><input type="checkbox" checked={visible.includes(column.key)} onChange={() => toggle(column.key)} />{column.label}</label>)}</div></details>; }
function AuditDrawer({ event, columns, onClose }) { return <ResponsiveSheet open={Boolean(event)} onOpenChange={(next) => !next && onClose()} title={event ? cleanAction(event.action) : 'Audit evidence'} description="Recorded values and request evidence for this audited action."><div className="space-y-3">{event && columns.map((column) => <div key={column.key} className={`rounded-xl border p-4 ${['oldValue','newValue'].includes(column.key) ? 'border-primary/20 bg-primary/[.035]' : 'border-border bg-background'}`}><p className="text-[11px] font-bold uppercase tracking-wide text-muted-foreground">{column.label}</p><pre className="mt-1 whitespace-pre-wrap break-words font-sans text-sm font-medium">{display(event[column.key])}</pre></div>)}</div></ResponsiveSheet>; }
function cleanAction(value = '') { return String(value).replaceAll('_',' '); }
function display(value) { if (value === null || value === undefined || value === '') return '—'; return typeof value === 'object' ? JSON.stringify(value,null,2) : String(value); }
function iso(date) { return date.toISOString().slice(0,10); }
function dateRange(shortcut) { const today = new Date(); const start = new Date(today); if (shortcut === 'all') return { dateFrom: '', dateTo: '' }; if (shortcut === '7days') start.setDate(today.getDate() - 6); if (shortcut === 'month') start.setDate(1); if (shortcut === 'year') { start.setMonth(0); start.setDate(1); } return { dateFrom: iso(shortcut === 'today' ? today : start), dateTo: iso(today) }; }
function saveBlob({ blob, filename }) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
