import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Archive, Download, Eye, FileLock2, FileText } from 'lucide-react';
import { getBatchPayslipsZip, getPayrollBatches, getStaffPayslipPdf } from '@/api/portalClient';
import { EmptyHint, PageHeader, PrimaryButton, SecondaryButton, StatusBadge } from '@/components/payroll/PageElements';
import { toast } from '@/components/ui/use-toast';

const Card = ({ children, className = '' }) => <section className={`rounded-xl border border-border bg-card p-5 ${className}`}>{children}</section>;
const inputClass = 'h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';

export default function PayslipPdfPage() {
  const [searchParams] = useSearchParams();
  const [batches, setBatches] = useState([]);
  const [selectedId, setSelectedId] = useState('');
  const [passwordRule, setPasswordRule] = useState('none');
  const [customPassword, setCustomPassword] = useState('');
  const [busyKey, setBusyKey] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { getPayrollBatches().then((rows) => { const ready = rows.filter((batch) => ['approved', 'generated', 'partially_sent', 'sent'].includes(batch.status)); setBatches(ready); const requested = searchParams.get('batch'); setSelectedId(ready.some((item) => item.id === requested) ? requested : ready[0]?.id || ''); }).catch((err) => setError(err.message)); }, [searchParams]);
  const batch = batches.find((item) => item.id === selectedId);
  const options = { passwordRule, customPassword };
  const validatePassword = () => { if (passwordRule === 'custom' && customPassword.trim().length < 6) { toast.warning('Custom PDF passwords must contain at least 6 characters.', { title: 'Password is too short' }); return false; } return true; };
  const preview = async (entry) => { if (!validatePassword()) return; const popup = window.open('', '_blank'); setBusyKey(`preview-${entry.staffRecordId}`); try { const { blob } = await getStaffPayslipPdf(batch.id, entry.staffRecordId, options); const url = URL.createObjectURL(blob); if (popup) popup.location.href = url; else window.open(url, '_blank'); window.setTimeout(() => URL.revokeObjectURL(url), 60000); setError(''); } catch (err) { popup?.close(); setError(err.message); } finally { setBusyKey(''); } };
  const download = async (entry) => { if (!validatePassword()) return; setBusyKey(`download-${entry.staffRecordId}`); try { const file = await getStaffPayslipPdf(batch.id, entry.staffRecordId, options, true); saveBlob(file); setError(''); toast.success(`${entry.fullName}'s confidential PDF is downloading.`, { title: 'Payslip ready' }); } catch (err) { toast.error(err.message, { title: 'PDF download failed' }); } finally { setBusyKey(''); } };
  const downloadAll = async () => { if (!batch || !validatePassword()) return; setBusyKey('zip'); try { const file = await getBatchPayslipsZip(batch.id, options); saveBlob(file); setError(''); toast.success(`${batch.entries?.length || 0} payslips were packaged into a secure ZIP file.`, { title: 'Payslip archive ready' }); } catch (err) { toast.error(err.message, { title: 'ZIP download failed' }); } finally { setBusyKey(''); } };
  return <div className="space-y-6"><PageHeader title="Payslip PDF Preview" description="Generate confidential, database-backed PDF payslips for each staff member before delivery." actions={batch ? <PrimaryButton disabled={busyKey === 'zip'} onClick={downloadAll}><Archive className="h-4 w-4" />{busyKey === 'zip' ? 'Building ZIP…' : 'Download All Payslips'}</PrimaryButton> : null} />
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-5 lg:grid-cols-[1.25fr,.75fr]"><Card><label className="text-xs font-bold uppercase text-muted-foreground">Approved payroll batch</label><select className={`${inputClass} mt-2`} value={selectedId} onChange={(e) => setSelectedId(e.target.value)}><option value="">Select an approved payroll</option>{batches.map((item) => <option key={item.id} value={item.id}>{item.name} · Version {item.version || 1} · {statusLabel(item.status)}</option>)}</select>{batch && <div className="mt-4 grid grid-cols-2 gap-3 rounded-lg bg-primary/[.04] p-4 sm:grid-cols-4"><Info label="Period" value={batch.period} /><Info label="Version" value={batch.version || 1} /><Info label="Staff" value={batch.entries?.length || 0} /><div><p className="text-xs text-muted-foreground">Status</p><div className="mt-1"><StatusBadge status={statusLabel(batch.status)} /></div></div></div>}</Card><Card><div className="flex items-center gap-2"><FileLock2 className="h-5 w-5 text-primary" /><h2 className="font-heading text-lg font-bold">PDF password</h2></div><select className={`${inputClass} mt-4`} value={passwordRule} onChange={(e) => setPasswordRule(e.target.value)}><option value="none">No password</option><option value="staff_id">Staff ID</option><option value="phone">Phone number</option><option value="custom">Custom password</option></select>{passwordRule === 'custom' && <input className={`${inputClass} mt-3`} type="password" value={customPassword} onChange={(e) => setCustomPassword(e.target.value)} placeholder="At least 6 characters" />}<p className="mt-3 text-xs leading-5 text-muted-foreground">Password protection is applied separately to every PDF, including files inside the ZIP archive.</p></Card></div>
    <Card><div className="mb-4 flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /><div><h2 className="font-heading text-lg font-bold">Staff payslips</h2><p className="text-sm text-muted-foreground">Preview the final page or download an individual PDF.</p></div></div><div className="divide-y divide-border">{batch?.entries?.map((entry) => <div key={entry.staffRecordId} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">{initials(entry.fullName)}</span><div className="min-w-0 flex-1"><p className="font-semibold">{entry.fullName}</p><p className="truncate text-xs text-muted-foreground">{entry.staffId} · {entry.department} · {entry.branch}</p></div><div className="flex gap-2"><SecondaryButton disabled={Boolean(busyKey)} onClick={() => preview(entry)}><Eye className="h-4 w-4" />{busyKey === `preview-${entry.staffRecordId}` ? 'Opening…' : 'Preview PDF'}</SecondaryButton><SecondaryButton disabled={Boolean(busyKey)} onClick={() => download(entry)}><Download className="h-4 w-4" />{busyKey === `download-${entry.staffRecordId}` ? 'Preparing…' : 'Download PDF'}</SecondaryButton></div></div>)}{!batch?.entries?.length && <EmptyHint>No submitted payroll is available for PDF generation.</EmptyHint>}</div></Card>
    <p className="text-center text-xs text-muted-foreground">Every PDF is marked confidential and generated from the saved payroll database. Spreadsheet formulas and error references are never used.</p>
  </div>;
}

function saveBlob({ blob, filename }) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function initials(name = '') { return name.split(' ').filter(Boolean).map((part) => part[0]).slice(0, 2).join('').toUpperCase(); }
function statusLabel(status) { return ({ approved: 'Approved', generated: 'Generated', partially_sent: 'Partially Sent', sent: 'Sent' })[status] || status; }
function Info({ label, value }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
