import React, { useEffect, useMemo, useState } from 'react';
import { ArchiveRestore, Building2, DatabaseBackup, Download, FileCheck2, Image, Landmark, Mail, Save, Send, ServerCog, Shield, Upload } from 'lucide-react';
import { downloadSecureBackup, getSecurityStatus, getSystemSettings, restoreSecureBackup, testPdfConfiguration, testSmtpConfiguration, updatePortalSettings, uploadBrandingAsset } from '@/api/portalClient';
import { PageHeader, PrimaryButton, SecondaryButton, StatusBadge } from '@/components/payroll/PageElements';
import { Switch } from '@/components/ui/switch';
import { toast } from '@/components/ui/use-toast';
import ConfirmActionDialog from '@/components/ui/confirm-action-dialog';

/** @type {Array<[string, string, React.ComponentType<any>]>} */
const TABS = [
  ['branding','Branding',Building2], ['organization','Organization',Landmark], ['payroll','Payroll',ServerCog], ['email','Email',Mail],
  ['security','Security',Shield], ['pdf','PDF',Image], ['backup','Backup',DatabaseBackup],
];
const SECTION_KEYS = {
  branding: ['bankName','shortBankName','bankAddress','bankLogo','authorizedSignature','emailFooter','portalName','loginSubtitle','loginButtonText','authorizedAccessText','allowLightMode','allowDarkMode','defaultTheme'],
  organization: ['emailDomain','branches','departments'],
  payroll: ['payrollApprovalRequired','inactiveStaffInHistoricalReports','contributionRates','contributionRateEffectiveMonth','payrollValidationRules'],
  email: ['emailProvider','smtpServer','smtpPort','smtpSecurity','smtpUsername','smtpSender','defaultEmailSubject','defaultEmailBody','requireTestEmail'],
  security: ['requirePrivilegedMfa','sessionTimeoutMinutes','passwordResetMinutes','restrictPayslipDownloads'],
  pdf: ['payslipTitle','confidentialityNote','pdfPasswordRule','allowanceLabels','deductionLabels','employerContributionLabels'],
  backup: ['backupSchedule','auditRetentionYears','payrollRetentionYears','deliveryRetentionYears'],
};
const card = 'rounded-xl border border-border bg-card p-4 sm:p-5';
const input = 'mt-1.5 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';
const areas = 'mt-1.5 min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';

export default function Settings() {
  const [settings, setSettings] = useState(null);
  const [baseline, setBaseline] = useState(null);
  const [security, setSecurity] = useState(null);
  const [activeTab, setActiveTab] = useState('branding');
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const [backupFile, setBackupFile] = useState(null);
  const [confirmation, setConfirmation] = useState('');
  const [pendingDanger, setPendingDanger] = useState(null);

  const load = async () => { try { const [portal,status] = await Promise.all([getSystemSettings(),getSecurityStatus()]); setSettings(portal); setBaseline(portal); setSecurity(status); setError(''); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const dirtySections = useMemo(() => settings && baseline ? TABS.map(([key]) => key).filter((section) => SECTION_KEYS[section].some((key) => JSON.stringify(settings[key]) !== JSON.stringify(baseline[key]))) : [], [settings,baseline]);
  useEffect(() => { const warning = (event) => { if (!dirtySections.length) return; event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload',warning); return () => window.removeEventListener('beforeunload',warning); }, [dirtySections.length]);
  const change = (key,value) => setSettings((current) => ({ ...current, [key]: value }));
  const changeLabel = (group,key,value) => setSettings((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const changeNested = (group,key,value) => setSettings((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const saveSection = async (section) => {
    if (section === 'security' && pendingDanger !== 'security-save') { setPendingDanger('security-save'); return; }
    setPendingDanger(null); setBusy(`save-${section}`);
    const draft = settings;
    const payload = { ...baseline };
    SECTION_KEYS[section].forEach((key) => { payload[key] = draft[key]; });
    try {
      const updated = await updatePortalSettings(payload);
      setBaseline(updated);
      setSettings((current) => { const preserved = { ...updated }; TABS.map(([key]) => key).filter((key) => key !== section).forEach((other) => SECTION_KEYS[other].forEach((key) => { preserved[key] = current[key]; })); return preserved; });
      setError(''); toast.success(`${tabLabel(section)} settings were saved and recorded in the audit trail.`, { title: 'Section saved' });
    } catch (err) { setError(err.message); toast.error(err.message, { title: 'Settings were not saved' }); }
    finally { setBusy(''); }
  };
  const upload = async (file,key) => { if (!file) return; setBusy(key); try { const asset = await uploadBrandingAsset(file,key); change(key,asset.url); toast.success('The asset is ready. Save the Branding section to apply it.', { title: 'Upload complete' }); } catch (err) { setError(err.message); } finally { setBusy(''); } };
  const testSmtp = async () => { setBusy('smtp-test'); try { await testSmtpConfiguration(); toast.success('The saved SMTP server accepted a secure authenticated connection. No staff email was sent.', { title: 'SMTP test passed' }); } catch (err) { toast.error(err.message, { title: 'SMTP test failed' }); } finally { setBusy(''); } };
  const testPdf = async () => { setBusy('pdf-test'); try { await testPdfConfiguration(); toast.success('A sample payslip was generated successfully from the saved PDF configuration.', { title: 'PDF test passed' }); } catch (err) { toast.error(err.message, { title: 'PDF test failed' }); } finally { setBusy(''); } };
  const backup = async () => { setBusy('backup-download'); try { saveBlob(await downloadSecureBackup()); toast.success('The encrypted backup download has started.', { title: 'Backup prepared' }); } catch (err) { toast.error(err.message, { title: 'Backup failed' }); } finally { setBusy(''); } };
  const restore = async () => { setPendingDanger(null); if (!backupFile || confirmation !== 'RESTORE') return; setBusy('restore'); try { await restoreSecureBackup(await fileToBase64(backupFile),confirmation); window.location.href = '/login'; } catch (err) { setError(err.message); toast.error(err.message, { title: 'Restore failed' }); } finally { setBusy(''); } };

  if (!settings || !security) return <div><PageHeader title="Portal Control" description="Loading secure platform controls…" />{error && <Banner>{error}</Banner>}</div>;
  const tabDirty = dirtySections.includes(activeTab);
  const posture = [
    ['Password hashing',true], ['Inactivity logout',true], ['Account lockout',true],
    ['HTTPS',security.forceHttps], ['Payroll encryption',security.dataEncryptionConfigured],
    ['MFA encryption',security.mfaEncryptionConfigured], ['Backup encryption',security.backupEncryptionConfigured],
    ['SMTP credentials',security.smtpCredentialsConfigured], ['Delivery webhook',security.deliveryWebhookConfigured],
    ['Malware scanning',security.malwareScannerConfigured && (!security.malwareScannerRequired || security.malwareScannerConfigured)],
    ['Dedicated email worker',security.payslipWorkerMode === 'external' && security.payslipWorkerHealthy],
  ];

  return <div className="max-w-7xl space-y-6">
    <PageHeader title="Portal Control" description="Configure the platform without opening staff, payroll, payslip, delivery, report, or bank activity records." />
    <div className="rounded-xl border border-emerald-500/25 bg-emerald-500/[.06] p-4 text-sm"><b>Privacy boundary:</b> this control plane changes system policy and appearance only. Confidential bank operations remain outside the Boss Admin account.</div>
    {error && <Banner>{error}</Banner>}
    {dirtySections.length > 0 && <div className="sticky top-[72px] z-30 flex flex-col gap-3 rounded-xl border border-amber-500/30 bg-amber-50 p-4 text-amber-900 shadow-sm dark:bg-amber-950/40 dark:text-amber-200 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold">Unsaved changes: {dirtySections.map(tabLabel).join(', ')}. Save each section separately before leaving.</p>{tabDirty && <PrimaryButton disabled={Boolean(busy)} onClick={() => saveSection(activeTab)}><Save className="h-4 w-4" /> Save {tabLabel(activeTab)}</PrimaryButton>}</div>}
    <nav className="grid grid-cols-2 gap-2 rounded-xl border border-border bg-card p-2 sm:flex sm:overflow-x-auto">{TABS.map(([key,label,Icon]) => <button key={key} onClick={() => setActiveTab(key)} className={`relative flex min-h-11 min-w-0 items-center justify-center gap-2 rounded-lg px-3 text-xs font-semibold sm:shrink-0 sm:px-4 sm:text-sm ${activeTab === key ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'}`}><Icon className="h-4 w-4 shrink-0" /><span className="truncate">{label}</span>{dirtySections.includes(key) && <span className="h-2 w-2 shrink-0 rounded-full bg-amber-400" title="Unsaved changes" />}</button>)}</nav>

    {activeTab === 'branding' && <Section title="Branding" note="Bank identity, authentication wording, and appearance used throughout the platform."><div className="grid gap-4 sm:grid-cols-2"><Field label="Bank name"><Text value={settings.bankName} onChange={(value) => change('bankName',value)} /></Field><Field label="Short bank name"><Text value={settings.shortBankName} onChange={(value) => change('shortBankName',value)} /></Field><Field label="Platform name"><Text value={settings.portalName} onChange={(value) => change('portalName',value)} /></Field><Field label="Login button text"><Text value={settings.loginButtonText} onChange={(value) => change('loginButtonText',value)} /></Field></div><Field label="Login subtitle"><Text value={settings.loginSubtitle} onChange={(value) => change('loginSubtitle',value)} /></Field><Field label="Authorized access text"><Text value={settings.authorizedAccessText} onChange={(value) => change('authorizedAccessText',value)} /></Field><Field label="Bank address"><Text value={settings.bankAddress} onChange={(value) => change('bankAddress',value)} /></Field><Field label="Email footer"><textarea className={areas} value={settings.emailFooter} onChange={(event) => change('emailFooter',event.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><UploadBox label="Upload bank logo" current={settings.bankLogo} busy={busy === 'bankLogo'} onFile={(file) => upload(file,'bankLogo')} /><UploadBox label="Upload authorized signature" current={settings.authorizedSignature} busy={busy === 'authorizedSignature'} onFile={(file) => upload(file,'authorizedSignature')} /></div><div className="mt-4 space-y-3"><Policy label="Allow light mode" checked={settings.allowLightMode} onChange={(value) => change('allowLightMode',value)} /><Policy label="Allow dark mode" checked={settings.allowDarkMode} onChange={(value) => change('allowDarkMode',value)} /><Field label="Default theme"><select className={input} value={settings.defaultTheme} onChange={(event) => change('defaultTheme',event.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></Field></div><SaveSection name="branding" dirty={tabDirty} busy={busy} save={saveSection} /></Section>}

    {activeTab === 'organization' && <Section title="Organization" note="Lists used by registration, staff records, filters, and new payroll batches."><Field label="Official email domain"><Text value={settings.emailDomain} onChange={(value) => change('emailDomain',value)} /></Field><div className="grid gap-4 lg:grid-cols-2"><ListEditor label="Branches" values={settings.branches} onChange={(value) => change('branches',value)} /><ListEditor label="Departments" values={settings.departments} onChange={(value) => change('departments',value)} /></div><p className="mt-3 text-xs text-muted-foreground">Enter one item per line. Existing historical records keep their original branch and department values.</p><SaveSection name="organization" dirty={tabDirty} busy={busy} save={saveSection} /></Section>}

    {activeTab === 'payroll' && <Section title="Payroll" note="Rates and controls are snapshotted into each new batch; old payroll and sent payslips never change."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><RateField label="Employee SSF (%)" value={settings.contributionRates.employeeSsf} onChange={(value) => changeNested('contributionRates','employeeSsf',value)} /><RateField label="Employee ESP (%)" value={settings.contributionRates.employeeEsp} onChange={(value) => changeNested('contributionRates','employeeEsp',value)} /><RateField label="Employee PF (%)" value={settings.contributionRates.employeePf} onChange={(value) => changeNested('contributionRates','employeePf',value)} /><RateField label="Employer SSF (%)" value={settings.contributionRates.employerSsf} onChange={(value) => changeNested('contributionRates','employerSsf',value)} /><RateField label="Employer PF (%)" value={settings.contributionRates.employerPf} onChange={(value) => changeNested('contributionRates','employerPf',value)} /><Field label="Rates effective from"><input className={input} type="month" value={settings.contributionRateEffectiveMonth} onChange={(event) => change('contributionRateEffectiveMonth',event.target.value)} /></Field></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><MoneyField label="Basic salary warning limit" value={settings.payrollValidationRules.maxBasicSalary} onChange={(value) => changeNested('payrollValidationRules','maxBasicSalary',value)} /><MoneyField label="Other amount warning limit" value={settings.payrollValidationRules.maxOtherAmount} onChange={(value) => changeNested('payrollValidationRules','maxOtherAmount',value)} /><RateField label="Deduction warning (%)" value={settings.payrollValidationRules.deductionWarningPercent} onChange={(value) => changeNested('payrollValidationRules','deductionWarningPercent',value)} /></div><div className="mt-5 space-y-3"><Policy label="Require payroll approval" note="Only approved batches can be generated and sent." checked={settings.payrollApprovalRequired} onChange={(value) => change('payrollApprovalRequired',value)} /><Policy label="Show inactive staff in historical reports" note="Inactive staff remain excluded from every new payroll batch." checked={settings.inactiveStaffInHistoricalReports} onChange={(value) => change('inactiveStaffInHistoricalReports',value)} /></div><div className="mt-4 rounded-xl border border-emerald-500/25 bg-emerald-500/[.06] p-4 text-sm"><b>Bank control enforced:</b> approved payroll only. Percentage changes affect only batches for their effective month and later.</div><SaveSection name="payroll" dirty={tabDirty} busy={busy} save={saveSection} /></Section>}

    {activeTab === 'email' && <Section title="Email" note="Provider, connection details, template defaults, and test requirements."><div className="grid gap-4 sm:grid-cols-2"><Field label="Provider"><select className={input} value={settings.emailProvider} onChange={(event) => change('emailProvider',event.target.value)}><option value="smtp">SMTP</option><option value="microsoft365">Microsoft 365 SMTP</option><option value="gmail">Gmail SMTP</option><option value="sendgrid">SendGrid SMTP</option><option value="ses">Amazon SES SMTP</option></select></Field><Field label="SMTP security"><select className={input} value={settings.smtpSecurity} onChange={(event) => change('smtpSecurity',event.target.value)}><option value="ssl">SSL</option><option value="starttls">STARTTLS</option></select></Field><Field label="SMTP server"><Text value={settings.smtpServer} onChange={(value) => change('smtpServer',value)} /></Field><Field label="SMTP port"><input className={input} type="number" value={settings.smtpPort} onChange={(event) => change('smtpPort',Number(event.target.value))} /></Field><Field label="SMTP username"><Text value={settings.smtpUsername} onChange={(value) => change('smtpUsername',value)} /></Field><Field label="Sender address"><Text value={settings.smtpSender} onChange={(value) => change('smtpSender',value)} /></Field></div><p className="mt-3 rounded-lg bg-muted/50 p-3 text-xs text-muted-foreground">SMTP password: {settings.smtpPasswordConfigured ? 'configured securely on the server' : 'set MAIL_PASSWORD in the server environment'}. It is never stored in the browser.</p><Field label="Default email subject"><Text value={settings.defaultEmailSubject} onChange={(value) => change('defaultEmailSubject',value)} /></Field><Field label="Default email body"><textarea className={`${areas} min-h-40`} value={settings.defaultEmailBody} onChange={(event) => change('defaultEmailBody',event.target.value)} /></Field><Policy label="Require a test email before bulk sending" checked={settings.requireTestEmail} onChange={(value) => change('requireTestEmail',value)} /><div className="mt-5 flex flex-col gap-2 sm:flex-row sm:justify-between"><SecondaryButton disabled={tabDirty || Boolean(busy)} onClick={testSmtp}><Send className="h-4 w-4" />{busy === 'smtp-test' ? 'Testing…' : 'Test saved SMTP configuration'}</SecondaryButton><SaveSection name="email" dirty={tabDirty} busy={busy} save={saveSection} compact /></div>{tabDirty && <p className="mt-2 text-xs text-amber-700">Save Email settings before testing so the server uses the same values shown here.</p>}</Section>}

    {activeTab === 'security' && <><section className={card}><Heading icon={Shield} title="Security posture" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{posture.map(([label,ready]) => <div key={label} className="rounded-lg border border-border p-3"><StatusBadge status={ready ? 'Ready' : 'Action Required'} /><p className="mt-2 text-xs font-bold">{label}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Production readiness values come from server environment variables and cannot be enabled from the browser.</p></section><Section title="Security" note="Changes here affect access to confidential salary information and require confirmation."><div className="space-y-3"><Policy label="Require MFA for privileged roles" note="Administrators, finance officers, and approvers must enroll an authenticator." checked={settings.requirePrivilegedMfa} onChange={(value) => change('requirePrivilegedMfa',value)} /><Policy label="Restrict payslip downloads to authorized roles" checked={settings.restrictPayslipDownloads} onChange={(value) => change('restrictPayslipDownloads',value)} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Automatic logout after inactivity (minutes)"><input className={input} type="number" min="5" max="240" value={settings.sessionTimeoutMinutes} onChange={(event) => change('sessionTimeoutMinutes',Number(event.target.value))} /></Field><Field label="Password reset link lifetime (minutes)"><input className={input} type="number" min="5" max="240" value={settings.passwordResetMinutes} onChange={(event) => change('passwordResetMinutes',Number(event.target.value))} /></Field></div><SaveSection name="security" dirty={tabDirty} busy={busy} save={saveSection} /></Section></>}

    {activeTab === 'pdf' && <Section title="PDF" note="Payslip wording, contribution labels, and document password protection."><div className="grid gap-4 sm:grid-cols-2"><Field label="Payslip title"><Text value={settings.payslipTitle} onChange={(value) => change('payslipTitle',value)} /></Field><Field label="PDF password rule"><select className={input} value={settings.pdfPasswordRule} onChange={(event) => change('pdfPasswordRule',event.target.value)}><option value="staff_id">Staff ID</option><option value="phone">Phone number</option><option value="none">No password</option></select></Field></div><Field label="Confidentiality note"><Text value={settings.confidentialityNote} onChange={(value) => change('confidentialityNote',value)} /></Field><LabelEditor title="Allowance labels" values={settings.allowanceLabels} onChange={(key,value) => changeLabel('allowanceLabels',key,value)} /><LabelEditor title="Deduction labels" values={settings.deductionLabels} onChange={(key,value) => changeLabel('deductionLabels',key,value)} /><LabelEditor title="Employer contribution labels" values={settings.employerContributionLabels} onChange={(key,value) => changeLabel('employerContributionLabels',key,value)} /><div className="mt-5 flex flex-col gap-2 sm:flex-row sm:justify-between"><SecondaryButton disabled={tabDirty || Boolean(busy)} onClick={testPdf}><FileCheck2 className="h-4 w-4" />{busy === 'pdf-test' ? 'Testing…' : 'Test saved PDF configuration'}</SecondaryButton><SaveSection name="pdf" dirty={tabDirty} busy={busy} save={saveSection} compact /></div>{tabDirty && <p className="mt-2 text-xs text-amber-700">Save PDF settings before running the generation test.</p>}</Section>}

    {activeTab === 'backup' && <><Section title="Backup policy" note="Configure backup frequency and evidence-retention periods."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Backup schedule"><select className={input} value={settings.backupSchedule} onChange={(event) => change('backupSchedule',event.target.value)}><option value="off">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></Field><NumberField label="Audit retention (years)" value={settings.auditRetentionYears} change={(value) => change('auditRetentionYears',value)} /><NumberField label="Payroll retention (years)" value={settings.payrollRetentionYears} change={(value) => change('payrollRetentionYears',value)} /><NumberField label="Delivery log retention (years)" value={settings.deliveryRetentionYears} change={(value) => change('deliveryRetentionYears',value)} /></div><SaveSection name="backup" dirty={tabDirty} busy={busy} save={saveSection} /></Section>{settings.canManageBackups && <section className={card}><Heading icon={DatabaseBackup} title="Encrypted backup and restore" /><div className="grid gap-5 lg:grid-cols-2"><div><p className="text-sm text-muted-foreground">Manual backups are encrypted and exclude active sessions and reset tokens.</p><SecondaryButton className="mt-4" disabled={!security.backupEncryptionConfigured || Boolean(busy)} onClick={backup}><Download className="h-4 w-4" />Download secure backup</SecondaryButton></div><div><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed p-3 text-sm"><Upload className="h-4 w-4" />{backupFile?.name || 'Choose .bcbbackup'}<input className="hidden" type="file" accept=".bcbbackup" onChange={(event) => setBackupFile(event.target.files?.[0] || null)} /></label><input className={input} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="Type RESTORE" /><button className="mt-3 rounded-lg border border-red-500/40 px-4 py-2 text-sm font-bold text-red-700 disabled:opacity-40" disabled={!backupFile || confirmation !== 'RESTORE' || Boolean(busy)} onClick={() => setPendingDanger('restore')}><ArchiveRestore className="mr-2 inline h-4 w-4" />Restore database</button></div></div></section>}</>}

    <ConfirmActionDialog open={pendingDanger === 'security-save'} title="Apply security policy changes?" description="These changes can alter user access, MFA enforcement, session expiry, and payslip download rights. Confirm that the new policy is approved." confirmLabel="Apply security changes" tone="danger" busy={Boolean(busy)} onClose={() => setPendingDanger(null)} onConfirm={() => saveSection('security')} />
    <ConfirmActionDialog open={pendingDanger === 'restore'} title="Restore this database backup?" description="Restore is a high-impact operation. Current data will be replaced by the selected encrypted backup and all users will need to sign in again." confirmLabel="Restore database" tone="danger" busy={busy === 'restore'} onClose={() => setPendingDanger(null)} onConfirm={restore} />
  </div>;
}

function Section({ title,note,children }) { return <section className={card}><div className="mb-5"><h2 className="font-heading text-xl font-bold">{title}</h2><p className="text-sm text-muted-foreground">{note}</p></div>{children}</section>; }
function SaveSection({ name,dirty,busy,save,compact = false }) { return <div className={compact ? '' : 'mt-6 flex justify-end border-t border-border pt-4'}><PrimaryButton disabled={!dirty || Boolean(busy)} onClick={() => save(name)}><Save className="h-4 w-4" />{busy === `save-${name}` ? 'Saving…' : `Save ${tabLabel(name)}`}</PrimaryButton></div>; }
function Heading({ icon: Icon,title }) { return <div className="mb-4 flex items-center gap-2"><Icon className="h-5 w-5 text-primary" /><h2 className="font-heading text-lg font-bold">{title}</h2></div>; }
function Field({ label,children }) { return <label className="mt-3 block text-sm font-semibold">{label}{children}</label>; }
function Text({ value = '',onChange }) { return <input className={input} value={value} onChange={(event) => onChange(event.target.value)} />; }
function NumberField({ label,value,change }) { return <Field label={label}><input className={input} type="number" min="1" max="25" value={value} onChange={(event) => change(Number(event.target.value))} /></Field>; }
function RateField({ label,value,onChange }) { return <Field label={label}><input className={input} type="number" min="0" max="100" step="0.01" value={value} onChange={(event) => onChange(Number(event.target.value))} /></Field>; }
function MoneyField({ label,value,onChange }) { return <Field label={label}><div className="relative"><span className="absolute left-3 top-[18px] text-xs font-bold text-muted-foreground">GH₵</span><input className={`${input} pl-11`} type="number" min="1" max="100000000" step="100" value={value} onChange={(event) => onChange(Number(event.target.value))} /></div></Field>; }
function ListEditor({ label,values = [],onChange }) { return <Field label={label}><textarea className={`${areas} min-h-52`} value={values.join('\n')} onChange={(event) => onChange(event.target.value.split(/\r?\n/))} /></Field>; }
function Policy({ label,note = '',checked,onChange }) { return <div className="flex items-center justify-between gap-4 rounded-lg bg-muted/40 p-3"><div><p className="text-sm font-semibold">{label}</p>{note && <p className="text-xs text-muted-foreground">{note}</p>}</div><Switch checked={Boolean(checked)} onCheckedChange={onChange} /></div>; }
function LabelEditor({ title,values = {},onChange }) { return <div className="mt-4"><p className="text-xs font-bold uppercase text-muted-foreground">{title}</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(values).map(([key,value]) => <label key={key} className="text-[10px] text-muted-foreground">{key}<input className="mt-1 h-9 w-full rounded-lg border border-border bg-background px-3 text-xs text-foreground" value={value} onChange={(event) => onChange(key,event.target.value)} /></label>)}</div></div>; }
function UploadBox({ label,current,busy,onFile }) { return <label className="mt-3 flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-border p-3 text-sm"><Upload className="h-4 w-4 text-primary" /><span className="min-w-0"><b>{busy ? 'Uploading…' : label}</b><small className="block truncate text-muted-foreground">{current || 'PNG, JPG or WebP'}</small></span><input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => onFile(event.target.files?.[0])} /></label>; }
function Banner({ children }) { return <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{children}</div>; }
function tabLabel(key) { return TABS.find(([value]) => value === key)?.[1] || key; }
function saveBlob({ blob,filename }) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); window.setTimeout(() => URL.revokeObjectURL(url),1000); }
function fileToBase64(file) { return new Promise((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file); }); }
