import React, { useEffect, useState } from 'react';
import { ArchiveRestore, Building2, DatabaseBackup, Download, Image, Mail, Save, ServerCog, Shield, Upload } from 'lucide-react';
import { downloadSecureBackup, getSecurityStatus, getSystemSettings, restoreSecureBackup, updatePortalSettings, uploadBrandingAsset } from '@/api/portalClient';
import { PageHeader, PrimaryButton, SecondaryButton, StatusBadge } from '@/components/payroll/PageElements';
import { Switch } from '@/components/ui/switch';
import { toast } from '@/components/ui/use-toast';

const card = 'rounded-xl border border-border bg-card p-5';
const input = 'mt-1.5 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';
const areas = 'mt-1.5 min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary/25';

export default function Settings() {
  const [settings, setSettings] = useState(null); const [security, setSecurity] = useState(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const [backupFile, setBackupFile] = useState(null); const [confirmation, setConfirmation] = useState('');
  const [activeTab, setActiveTab] = useState('identity');
  const load = async () => { try { const [portal, status] = await Promise.all([getSystemSettings(), getSecurityStatus()]); setSettings(portal); setSecurity(status); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const change = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  const changeLabel = (group, key, value) => setSettings((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const save = async () => { setBusy('save'); try { const updated = await updatePortalSettings(settings); setSettings(updated); setError(''); toast.success('Changes were saved and recorded in the audit trail.', { title: 'Settings saved' }); } catch (err) { setError(err.message); toast.error(err.message, { title: 'Settings were not saved' }); } finally { setBusy(''); } };
  const upload = async (file, key) => { if (!file) return; setBusy(key); try { const asset = await uploadBrandingAsset(file, key); change(key, asset.url); setError(''); toast.success(`${key === 'bankLogo' ? 'Bank logo' : 'Authorized signature'} uploaded. Save settings to apply it.`, { title: 'Upload complete' }); } catch (err) { setError(err.message); toast.error(err.message, { title: 'Upload failed' }); } finally { setBusy(''); } };
  const backup = async () => { setBusy('backup'); try { saveBlob(await downloadSecureBackup()); toast.success('The encrypted backup download has started.', { title: 'Backup prepared' }); } catch (err) { setError(err.message); toast.error(err.message, { title: 'Backup failed' }); } finally { setBusy(''); } };
  const restore = async () => { if (!backupFile || confirmation !== 'RESTORE') return; setBusy('restore'); try { await restoreSecureBackup(await fileToBase64(backupFile), confirmation); window.location.href = '/login'; } catch (err) { setError(err.message); } finally { setBusy(''); } };
  if (!settings || !security) return <div><PageHeader title="System Settings" description="Loading customization settings…" />{error && <Banner tone="red">{error}</Banner>}</div>;
  const posture = [['Password hashing', true], ['Inactivity logout', true], ['Account lockout', true], ['HTTPS', security.forceHttps], ['Payroll encryption', security.dataEncryptionConfigured], ['Backup encryption', security.backupEncryptionConfigured]];
  return <div className="max-w-7xl space-y-6"><PageHeader title="System Settings and Customization" description="Branding, payslip, email, payroll, appearance, and security controls." actions={<PrimaryButton disabled={Boolean(busy)} onClick={save}><Save className="h-4 w-4" />{busy === 'save' ? 'Saving…' : 'Save All Settings'}</PrimaryButton>} />
    {error && <Banner tone="red">{error}</Banner>}
    <div className="flex gap-2 overflow-x-auto rounded-xl border border-border bg-card p-2">{[['identity','Identity'],['payslip','Payslip'],['email','Email'],['policies','Policies'],['security','Security & Backup']].map(([key, label]) => <button key={key} onClick={() => setActiveTab(key)} className={`min-h-10 shrink-0 rounded-lg px-4 text-sm font-semibold ${activeTab === key ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'}`}>{label}</button>)}</div>
    {activeTab === 'security' && <section className={card}><Heading icon={Shield} title="Security posture" /><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{posture.map(([label, ready]) => <div key={label} className="rounded-lg border border-border p-3"><StatusBadge status={ready ? 'Ready' : 'Action Required'} /><p className="mt-2 text-xs font-bold">{label}</p></div>)}</div></section>}
    <div className="grid gap-5 xl:grid-cols-2">
      {activeTab === 'identity' && <section className={card}><Heading icon={Building2} title="Bank identity" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Bank name"><Text value={settings.bankName} onChange={(v) => change('bankName', v)} /></Field><Field label="Payslip title"><Text value={settings.payslipTitle} onChange={(v) => change('payslipTitle', v)} /></Field></div><Field label="Bank address"><Text value={settings.bankAddress} onChange={(v) => change('bankAddress', v)} /></Field><Field label="Confidentiality note"><Text value={settings.confidentialityNote} onChange={(v) => change('confidentialityNote', v)} /></Field><Field label="Email footer"><textarea className={areas} value={settings.emailFooter} onChange={(e) => change('emailFooter', e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><UploadBox label="Upload bank logo" current={settings.bankLogo} busy={busy === 'bankLogo'} onFile={(f) => upload(f, 'bankLogo')} /><UploadBox label="Upload signature" current={settings.authorizedSignature} busy={busy === 'authorizedSignature'} onFile={(f) => upload(f, 'authorizedSignature')} /></div></section>}
      {activeTab === 'payslip' && <section className={card}><Heading icon={Image} title="Payslip labels and protection" /><LabelEditor title="Allowance labels" values={settings.allowanceLabels} onChange={(k, v) => changeLabel('allowanceLabels', k, v)} /><LabelEditor title="Deduction labels" values={settings.deductionLabels} onChange={(k, v) => changeLabel('deductionLabels', k, v)} /><LabelEditor title="Employer contribution labels" values={settings.employerContributionLabels} onChange={(k, v) => changeLabel('employerContributionLabels', k, v)} /><Field label="Default PDF password"><select className={input} value={settings.pdfPasswordRule} onChange={(e) => change('pdfPasswordRule', e.target.value)}><option value="staff_id">Staff ID</option><option value="phone">Phone number</option><option value="none">No password</option></select></Field></section>}
      {activeTab === 'email' && <section className={card}><Heading icon={Mail} title="Email delivery" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Provider"><select className={input} value={settings.emailProvider} onChange={(e) => change('emailProvider', e.target.value)}><option value="smtp">SMTP</option><option value="microsoft365">Microsoft 365 SMTP</option><option value="gmail">Gmail SMTP</option><option value="sendgrid">SendGrid SMTP</option><option value="ses">Amazon SES SMTP</option></select></Field><Field label="SMTP security"><select className={input} value={settings.smtpSecurity} onChange={(e) => change('smtpSecurity', e.target.value)}><option value="ssl">SSL</option><option value="starttls">STARTTLS</option></select></Field><Field label="SMTP server"><Text value={settings.smtpServer} onChange={(v) => change('smtpServer', v)} /></Field><Field label="SMTP port"><input className={input} type="number" value={settings.smtpPort} onChange={(e) => change('smtpPort', Number(e.target.value))} /></Field><Field label="SMTP username"><Text value={settings.smtpUsername} onChange={(v) => change('smtpUsername', v)} /></Field><Field label="Sender address"><Text value={settings.smtpSender} onChange={(v) => change('smtpSender', v)} /></Field></div><p className="mt-3 rounded-lg bg-muted/50 p-3 text-xs text-muted-foreground">SMTP password: {settings.smtpPasswordConfigured ? 'configured securely on the server' : 'set MAIL_PASSWORD in the server environment'}. Passwords are never stored in browser settings.</p><Field label="Default email subject"><Text value={settings.defaultEmailSubject} onChange={(v) => change('defaultEmailSubject', v)} /></Field><Field label="Default email body"><textarea className={`${areas} min-h-40`} value={settings.defaultEmailBody} onChange={(e) => change('defaultEmailBody', e.target.value)} /></Field></section>}
      {activeTab === 'policies' && <section className={card}><Heading icon={ServerCog} title="Payroll, retention, and appearance policies" /><div className="space-y-3"><Policy label="Require privileged-role MFA" note="Required for administrators, finance officers, and approvers." checked={settings.requirePrivilegedMfa} onChange={(v) => change('requirePrivilegedMfa', v)} /><Policy label="Require payroll approval" note="Salary changes always require approval, even when this is off." checked={settings.payrollApprovalRequired} onChange={(v) => change('payrollApprovalRequired', v)} /><Policy label="Require test email before bulk sending" checked={settings.requireTestEmail} onChange={(v) => change('requireTestEmail', v)} /><Policy label="Show inactive staff in historical reports" note="Inactive staff remain excluded from every new payroll batch." checked={settings.inactiveStaffInHistoricalReports} onChange={(v) => change('inactiveStaffInHistoricalReports', v)} /><Policy label="Allow light mode" checked={settings.allowLightMode} onChange={(v) => change('allowLightMode', v)} /><Policy label="Allow dark mode" checked={settings.allowDarkMode} onChange={(v) => change('allowDarkMode', v)} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Default theme"><select className={input} value={settings.defaultTheme} onChange={(e) => change('defaultTheme', e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></Field><Field label="Backup schedule"><select className={input} value={settings.backupSchedule} onChange={(e) => change('backupSchedule', e.target.value)}><option value="off">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></Field><Field label="Automatic logout (minutes)"><input className={input} type="number" min="5" max="240" value={settings.sessionTimeoutMinutes} onChange={(e) => change('sessionTimeoutMinutes', Number(e.target.value))} /></Field><Field label="Audit retention (years)"><input className={input} type="number" min="1" max="25" value={settings.auditRetentionYears} onChange={(e) => change('auditRetentionYears', Number(e.target.value))} /></Field><Field label="Payroll retention (years)"><input className={input} type="number" min="1" max="25" value={settings.payrollRetentionYears} onChange={(e) => change('payrollRetentionYears', Number(e.target.value))} /></Field><Field label="Delivery-log retention (years)"><input className={input} type="number" min="1" max="25" value={settings.deliveryRetentionYears} onChange={(e) => change('deliveryRetentionYears', Number(e.target.value))} /></Field></div><p className="mt-3 text-xs text-muted-foreground">Retention changes define bank policy and are audited. Immutable payroll and audit records are never silently deleted; approved archival procedures must be used.</p></section>}
    </div>
    {activeTab === 'security' && settings.canManageBackups && <section className={card}><Heading icon={DatabaseBackup} title="Encrypted backup and restore" /><div className="grid gap-5 lg:grid-cols-2"><div><p className="text-sm text-muted-foreground">Schedule: <b>{settings.backupSchedule}</b>. Manual backups are encrypted and exclude active sessions and reset tokens.</p><SecondaryButton className="mt-4" disabled={!security.backupEncryptionConfigured || Boolean(busy)} onClick={backup}><Download className="h-4 w-4" />Download Secure Backup</SecondaryButton></div><div><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed p-3 text-sm"><Upload className="h-4 w-4" />{backupFile?.name || 'Choose .bcbbackup'}<input className="hidden" type="file" accept=".bcbbackup" onChange={(e) => setBackupFile(e.target.files?.[0] || null)} /></label><input className={input} value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder="Type RESTORE" /><button className="mt-3 rounded-lg border border-red-500/40 px-4 py-2 text-sm font-bold text-red-700 disabled:opacity-40" disabled={!backupFile || confirmation !== 'RESTORE' || Boolean(busy)} onClick={restore}><ArchiveRestore className="mr-2 inline h-4 w-4" />Restore Database</button></div></div></section>}
  </div>;
}

function Heading({ icon: Icon, title }) { return <div className="mb-4 flex items-center gap-2"><Icon className="h-5 w-5 text-primary" /><h2 className="font-heading text-lg font-bold">{title}</h2></div>; }
function Field({ label, children }) { return <label className="mt-3 block text-sm font-semibold">{label}{children}</label>; }
function Text({ value = '', onChange }) { return <input className={input} value={value} onChange={(e) => onChange(e.target.value)} />; }
function Policy({ label, note, checked, onChange }) { return <div className="flex items-center justify-between gap-4 rounded-lg bg-muted/40 p-3"><div><p className="text-sm font-semibold">{label}</p>{note && <p className="text-xs text-muted-foreground">{note}</p>}</div><Switch checked={Boolean(checked)} onCheckedChange={onChange} /></div>; }
function LabelEditor({ title, values = {}, onChange }) { return <div className="mt-4"><p className="text-xs font-bold uppercase text-muted-foreground">{title}</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(values).map(([key, value]) => <input key={key} aria-label={key} className="h-9 rounded-lg border border-border bg-background px-3 text-xs" value={value} onChange={(e) => onChange(key, e.target.value)} />)}</div></div>; }
function UploadBox({ label, current, busy, onFile }) { return <label className="mt-3 flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-border p-3 text-sm"><Upload className="h-4 w-4 text-primary" /><span className="min-w-0"><b>{busy ? 'Uploading…' : label}</b><small className="block truncate text-muted-foreground">{current || 'PNG, JPG or WebP'}</small></span><input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => onFile(e.target.files?.[0])} /></label>; }
function Banner({ tone, children }) { return <div className={`flex items-center gap-2 rounded-lg border p-3 text-sm ${tone === 'green' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700' : 'border-red-500/30 bg-red-500/10 text-red-700'}`}>{children}</div>; }
function saveBlob({ blob, filename }) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function fileToBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file); }); }
